_target_: models.tokenizer.OCTokenizer

vocab_size: 512
embed_dim: 7
encoder:
  _target_: models.tokenizer.SlotAttention
  config:
    _target_: models.tokenizer.SAConfig
    resolution: 64
    num_slots: 7
    iters: 3
    ch: 64
    hidden_dim: 512
decoder:
  _target_: models.tokenizer.SpatialBroadcastDecoder
  config:
    _target_: models.tokenizer.SBDecoderConfig
    num_slots: 7
    resolution: 64
    hidden_dim: 512